### PR TITLE
fix shift & add getStackTrace

### PR DESCRIPTION
**Pull request by f10w3r-s**

### CODE REVIEW

**Comment by huuck** [comment]
Oh, that looks really sweet! I'll do some sanity checks on the code and merge it ASAP! Thanks!

**Comment by f10w3r-s** [comment]
Thank you for creating a good project. It helped me a lot with my work.

**Comment by huuck** [comment]
PR looks good, but quick question: what is string_deob.py? It seems to contain some logic you used in your deobfuscation process. Is it specific only for that sample or can we extend it to do more generic deobfuscation?

**Comment by f10w3r-s** [comment]
Sorry... I haven't used GitHub much so I'm inexperienced.

I included it because I thought it would be helpful for first-time users when used with the example, but it is not an element of PR.

**Comment by huuck** [comment]
Ok. I'll exclude it in the PR. Thanks a lot for the support, reflection was
one thing I always wanted to implement.

**Comment by f10w3r-s** [comment]
thank you! :) I'm enjoying your blog.

**Comment by huuck** [comment]
merged. I will remove teh string_deobf.py and baksmali for now until you can put it in a more generic form.

**Comment by f10w3r-s** [comment]
Thank you! 
I committed by adding files and inflate-related functions to mocks. Could you please check this?


Also, in the int_to_char smali code part, I slightly modified the part that handles positive numbers as 1-byte. Looking at the dex reference, it says it should be calculated as 0xffff.

**Pull request merged**
